### PR TITLE
Remove `sbt-scoverage` and `sbt-coveralls` plugins

### PR DESCRIPTION
**Pull request by beatriz**
We aren't using the `sbt-coveralls` to report the coverage, so I removed it.

### CODE REVIEW

**Review by jcazevedo — APPROVED** [review]

**Comment by jcazevedo** [comment]
Do we need to keep sbt-scoverage then?

**Comment by beatriz** [comment]
> Do we need to keep sbt-scoverage then?

I left it because it allows us to generate coverage reports locally, it could be useful. But I don't have a strong opinion on this 😄

**Comment by jcazevedo** [comment]
> I left it because it allows us to generate coverage reports locally, it could be useful.

We can always set it up as a global plugin if we want to generate those reports locally. I think it's preferable to remove it.

**Comment by beatriz** [comment]
I've also removed `sbt-scoverage` and updated the PR title accordingly.

**Pull request merged**
